server:
  port: 80

spring:
  application:
    name: springcloud-consumer-80


# Eureka配置：配置服务注册中心地址
eureka:
  client:
    # 表示是否向 Eureka 注册中心注册自己，客户端的话为 ture（默认，客户端可不写）
    register-with-eureka: true
    # fetch-registry如果为false,则表示自己为注册中心,客户端的话为 ture（默认，客户端可不写）
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://192.168.42.185:7002/eureka/,http://127.0.0.1:7003/eureka/ #注册地址-集群
  instance:
    instance-id: springcloud-consumer-80

ribbon:
  ReadTimeout: 5000 #读取超时设置 5s
  ConnectTimeout: 5000 #连接超时设置 5s