server:
  port: 8002

spring:
  application:
    name: springcloud-provider

# Eureka配置：配置服务注册中心地址
eureka:
  client:
    # 表示是否向 Eureka 注册中心注册自己，客户端的话为 ture（默认，客户端可不写）
    register-with-eureka: true
    # fetch-registry如果为false,则表示自己为注册中心,客户端的话为 ture（默认，客户端可不写）
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://192.168.42.185:7002/eureka/,http://127.0.0.1:7003/eureka/
  instance:
    instance-id: springcloud-provider-8002 #修改Eureka上的默认描述信息
    prefer-ip-address: true

info:
  app.name: wm-vae
  company.name: 小白很无奈
feign:
  hystrix:
    enabled: true #开启降级